# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "47b7a0647d53324a7a1d34e3b2dfcdc3"
name = "my-demo-doc1-app"
application_url = "https://customize-sad-paint-aims.trycloudflare.com"
embedded = false
handle = "my-demo-doc1-app"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://customize-sad-paint-aims.trycloudflare.com/auth/callback", "https://customize-sad-paint-aims.trycloudflare.com/auth/shopify/callback", "https://customize-sad-paint-aims.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
